package vista;


import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import static vista.Index.panelSecundario;
import static vista.Index.panelGeneral;
import static vista.Registro.unAreaADM;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author ADMON
 */
public class AreaAdministracion extends javax.swing.JInternalFrame {

 // Objects Globales 
    
    DatosPersona ventanaPersona = new DatosPersona();
    public static DatosProducto ventanaProducto;
    
    
    
    
    public AreaAdministracion() {
        initComponents();
        cargarMetodos();
//        setLocationRelativeTo(null);
    }
    
    
    public void cargarMetodos(){
        agregarImgs();
        funcionesExtras();
    
    
    }
    
    
    private void agregarImgs(){
        
        
//       logo

           ImageIcon importarImg = (new ImageIcon("imgs/logoQ1.png"));
           JLabel logoImg =new JLabel();
           logoImg.setIcon(new ImageIcon(importarImg.getImage().getScaledInstance(35,35, Image.SCALE_SMOOTH)));
           logoImg.setBounds(63,17,68,68);
           panelAdministracion.add(logoImg);
//           panel.setComponentZOrder(logoImg, 0);
           

//      iconos 

     // Edificio
     
       ImageIcon importarIconoF = (new ImageIcon("imgs/edificio.png"));
       JLabel edificioImg =new JLabel();
       edificioImg.setIcon(new ImageIcon(importarIconoF.getImage().getScaledInstance(65,85, Image.SCALE_SMOOTH)));
       edificioImg.setBounds(44,45,65,85);
       panelFarmacia.add(edificioImg);
       
     // Persona
     
       ImageIcon importarIconoP = (new ImageIcon("imgs/persona.png"));
       JLabel personaImg =new JLabel();
       personaImg.setIcon(new ImageIcon(importarIconoP.getImage().getScaledInstance(80,65, Image.SCALE_SMOOTH)));
       personaImg.setBounds(33,60,80,65);
       panelPersona.add(personaImg);
       
     // Producto
     
       ImageIcon importarIconoC = (new ImageIcon("imgs/cajas.png"));
       JLabel productoImg = new JLabel();
       productoImg.setIcon(new ImageIcon(importarIconoC.getImage().getScaledInstance(70,75, Image.SCALE_SMOOTH)));
       productoImg.setBounds(42,50,70,75);
       panelProducto.add(productoImg);


    }
    
    private void funcionesExtras(){
    
         this.setBounds(290, 70, this.getWidth(), this.getHeight());        
//          this.setBounds(300, 70, 1000 , 750);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdministracion = new javax.swing.JPanel();
        vSuperOfertas = new javax.swing.JLabel();
        vSuperOfertas1 = new javax.swing.JLabel();
        panelFarmacia = new javax.swing.JPanel();
        btnIngresar1 = new javax.swing.JButton();
        panelPersona = new javax.swing.JPanel();
        btnIngresar8 = new javax.swing.JButton();
        panelProducto = new javax.swing.JPanel();
        btnIngresar3 = new javax.swing.JButton();
        panelAuditoria3 = new javax.swing.JPanel();
        btnIngresar5 = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelAdministracion.setBackground(new java.awt.Color(255, 255, 255));
        panelAdministracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        vSuperOfertas.setFont(new java.awt.Font("PT Sans Narrow", 0, 35)); // NOI18N
        vSuperOfertas.setText("Farmacit");
        vSuperOfertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vSuperOfertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vSuperOfertasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vSuperOfertasMouseExited(evt);
            }
        });

        vSuperOfertas1.setFont(new java.awt.Font("PT Sans Narrow", 0, 18)); // NOI18N
        vSuperOfertas1.setText("Area de administracion");
        vSuperOfertas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vSuperOfertas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vSuperOfertas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vSuperOfertas1MouseExited(evt);
            }
        });

        panelFarmacia.setBackground(new java.awt.Color(255, 255, 255));
        panelFarmacia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIngresar1.setBackground(new java.awt.Color(0, 102, 255));
        btnIngresar1.setFont(new java.awt.Font("PT Sans Narrow", 0, 20)); // NOI18N
        btnIngresar1.setText("Farmacias");
        btnIngresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresar1MouseClicked(evt);
            }
        });
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFarmaciaLayout = new javax.swing.GroupLayout(panelFarmacia);
        panelFarmacia.setLayout(panelFarmaciaLayout);
        panelFarmaciaLayout.setHorizontalGroup(
            panelFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFarmaciaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnIngresar1)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelFarmaciaLayout.setVerticalGroup(
            panelFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFarmaciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresar1)
                .addGap(15, 15, 15))
        );

        panelPersona.setBackground(new java.awt.Color(255, 255, 255));
        panelPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIngresar8.setBackground(new java.awt.Color(0, 102, 255));
        btnIngresar8.setFont(new java.awt.Font("PT Sans Narrow", 0, 20)); // NOI18N
        btnIngresar8.setText("Personas");
        btnIngresar8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresar8MouseClicked(evt);
            }
        });
        btnIngresar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPersonaLayout = new javax.swing.GroupLayout(panelPersona);
        panelPersona.setLayout(panelPersonaLayout);
        panelPersonaLayout.setHorizontalGroup(
            panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnIngresar8)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelPersonaLayout.setVerticalGroup(
            panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresar8)
                .addGap(17, 17, 17))
        );

        panelProducto.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIngresar3.setBackground(new java.awt.Color(0, 102, 255));
        btnIngresar3.setFont(new java.awt.Font("PT Sans Narrow", 0, 20)); // NOI18N
        btnIngresar3.setText("Productos");
        btnIngresar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresar3MouseClicked(evt);
            }
        });
        btnIngresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnIngresar3)
                .addGap(26, 26, 26))
        );
        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(btnIngresar3)
                .addGap(17, 17, 17))
        );

        panelAuditoria3.setBackground(new java.awt.Color(255, 255, 255));
        panelAuditoria3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIngresar5.setBackground(new java.awt.Color(0, 102, 255));
        btnIngresar5.setFont(new java.awt.Font("PT Sans Narrow", 0, 20)); // NOI18N
        btnIngresar5.setText("Auditoria");
        btnIngresar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresar5MouseClicked(evt);
            }
        });
        btnIngresar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAuditoria3Layout = new javax.swing.GroupLayout(panelAuditoria3);
        panelAuditoria3.setLayout(panelAuditoria3Layout);
        panelAuditoria3Layout.setHorizontalGroup(
            panelAuditoria3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuditoria3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnIngresar5)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelAuditoria3Layout.setVerticalGroup(
            panelAuditoria3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAuditoria3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresar5)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout panelAdministracionLayout = new javax.swing.GroupLayout(panelAdministracion);
        panelAdministracion.setLayout(panelAdministracionLayout);
        panelAdministracionLayout.setHorizontalGroup(
            panelAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministracionLayout.createSequentialGroup()
                .addGroup(panelAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdministracionLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(vSuperOfertas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vSuperOfertas1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdministracionLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(panelFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(panelAuditoria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(panelPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(panelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, Short.MAX_VALUE))
        );
        panelAdministracionLayout.setVerticalGroup(
            panelAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministracionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vSuperOfertas)
                    .addComponent(vSuperOfertas1))
                .addGap(55, 55, 55)
                .addGroup(panelAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAuditoria3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAdministracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        panelSecundario.setVisible(true);  
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnIngresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar3ActionPerformed
        
        ventanaProducto = new DatosProducto();
        ventanaProducto.setVisible(true);
        unAreaADM.setVisible(false);
        panelGeneral.add(ventanaProducto);
        
    }//GEN-LAST:event_btnIngresar3ActionPerformed

    private void btnIngresar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresar3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresar3MouseClicked

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
   
        
        DatosFarmacia ventanaFarmacia = new DatosFarmacia();
        ventanaFarmacia.setVisible(true);
        unAreaADM.setVisible(false);
        panelGeneral.add(ventanaFarmacia);
        
    }//GEN-LAST:event_btnIngresar1ActionPerformed

    private void btnIngresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresar1MouseClicked

    private void vSuperOfertas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vSuperOfertas1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_vSuperOfertas1MouseExited

    private void vSuperOfertas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vSuperOfertas1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_vSuperOfertas1MouseEntered

    private void vSuperOfertasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vSuperOfertasMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_vSuperOfertasMouseExited

    private void vSuperOfertasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vSuperOfertasMouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_vSuperOfertasMouseEntered

    private void btnIngresar8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresar8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresar8MouseClicked

    private void btnIngresar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar8ActionPerformed
        // TODO add your handling code here:

        ventanaPersona.setVisible(true);
        unAreaADM.setVisible(false);
        panelGeneral.add(ventanaPersona);
    }//GEN-LAST:event_btnIngresar8ActionPerformed

    private void btnIngresar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresar5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresar5MouseClicked

    private void btnIngresar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresar5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JButton btnIngresar3;
    private javax.swing.JButton btnIngresar5;
    private javax.swing.JButton btnIngresar8;
    private javax.swing.JPanel panelAdministracion;
    private javax.swing.JPanel panelAuditoria3;
    private javax.swing.JPanel panelFarmacia;
    private javax.swing.JPanel panelPersona;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JLabel vSuperOfertas;
    private javax.swing.JLabel vSuperOfertas1;
    // End of variables declaration//GEN-END:variables
}
