/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.controladorTipoPersona;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import modelo.TipoPersona;
import static vista.AreaAdministracion.ventanaProducto;
import static vista.Index.panelGeneral;

/**
 *
 * @author ADMON
 */
public class DatosTipoPersona extends javax.swing.JInternalFrame {

//    objetos Globales
     
      DatosPersona nuevaVentanaPersona;
      DefaultTableModel tabla;
      controladorTipoPersona controlarTipoPersona = new controladorTipoPersona();
    
    
    public DatosTipoPersona() {
        initComponents();
        cargarMetodos();
    }
    
    
    private void cargarMetodos(){
      funcionesExtras();
      cargarImagenes();
      llenarTabla();
    
    }
    
    
     private void funcionesExtras() {
        
        setLocation(320, 100);
//        spinnerId.setVisible(false);

    }
     
     private void cargarImagenes(){
     
          // logo 
           ImageIcon importarImg = (new ImageIcon("imgs/logoQ1.png"));
           JLabel logoImg =new JLabel();
           logoImg.setIcon(new ImageIcon(importarImg.getImage().getScaledInstance(25,25, Image.SCALE_SMOOTH)));
           logoImg.setBounds(434,490,25,25);
           panelTipoPersona.add(logoImg);
           
           // icono marca al lado izq 
           ImageIcon importarIconoF = (new ImageIcon("imgs/marcas.png"));
           JLabel edificioImg =new JLabel();
           edificioImg.setIcon(new ImageIcon(importarIconoF.getImage().getScaledInstance(34,38, Image.SCALE_SMOOTH)));
           edificioImg.setBounds(138,48,34,38);
           panelTipoPersona.add(edificioImg);
           
           // flecha izquierda
           ImageIcon importarFlecha = (new ImageIcon("imgs/flechaIzq.png"));
           JLabel iconoFlecha = new JLabel();
           iconoFlecha.setIcon(new ImageIcon(importarFlecha.getImage().getScaledInstance(33,33, Image.SCALE_SMOOTH)));
           iconoFlecha.setBounds(40,30,33,33);
           iconoFlecha.setCursor( new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR){});// curso de la mano
           panelTipoPersona.add(iconoFlecha);
           
           
           iconoFlecha.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseClicked(MouseEvent e) {
                retornarVentanaPersona();    
            }
        }
        );
     
     
     
     }
     
     private void retornarVentanaPersona(){
         
         nuevaVentanaPersona = new DatosPersona();
         this.setVisible(false);
         nuevaVentanaPersona.setVisible(true);
         panelGeneral.add(nuevaVentanaPersona);
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTipoPersona = new javax.swing.JPanel();
        vSuperOfertas = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreTipoPersona = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        spinnerId = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDatosTipoPersona = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        labelFarmacit = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelTipoPersona.setBackground(new java.awt.Color(255, 255, 255));

        vSuperOfertas.setFont(new java.awt.Font("PT Sans Narrow", 0, 35)); // NOI18N
        vSuperOfertas.setText("Tipos de personas");
        vSuperOfertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vSuperOfertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vSuperOfertasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vSuperOfertasMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("PT Sans Narrow", 0, 22)); // NOI18N
        jLabel10.setText("nombreTipoPersona");

        txtNombreTipoPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombreTipoPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTipoPersonaActionPerformed(evt);
            }
        });

        btnIngresar.setBackground(new java.awt.Color(0, 102, 255));
        btnIngresar.setFont(new java.awt.Font("PT Sans Narrow", 0, 18)); // NOI18N
        btnIngresar.setText("Insertar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setName("Insertar"); // NOI18N
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 102, 255));
        btnLimpiar.setFont(new java.awt.Font("PT Sans Narrow", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 102, 255));
        btnEliminar.setFont(new java.awt.Font("PT Sans Narrow", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setName("Eliminar"); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 102, 255));
        btnModificar.setFont(new java.awt.Font("PT Sans Narrow", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("PT Sans Narrow", 0, 24)); // NOI18N
        jLabel11.setText(" Ingresar una Marca");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        txtBuscar.setFont(new java.awt.Font("PT Sans Narrow", 0, 18)); // NOI18N
        txtBuscar.setText("  Buscar un tipo de persona ");
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        spinnerId.setEnabled(false);

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaDatosTipoPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idTipoPersona", "nombreTipoPersona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDatosTipoPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosTipoPersonaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaDatosTipoPersona);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        labelFarmacit.setFont(new java.awt.Font("PT Sans Narrow", 0, 25)); // NOI18N
        labelFarmacit.setText("Farmacit");
        labelFarmacit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelFarmacit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelFarmacitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelFarmacitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelTipoPersonaLayout = new javax.swing.GroupLayout(panelTipoPersona);
        panelTipoPersona.setLayout(panelTipoPersonaLayout);
        panelTipoPersonaLayout.setHorizontalGroup(
            panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                                .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                                        .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(btnLimpiar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnModificar))
                                            .addComponent(txtNombreTipoPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTipoPersonaLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)))
                                .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar)
                                    .addComponent(btnIngresar)
                                    .addComponent(spinnerId, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(vSuperOfertas)
                        .addGap(179, 179, 179)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTipoPersonaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelFarmacit)
                .addGap(432, 432, 432))
        );
        panelTipoPersonaLayout.setVerticalGroup(
            panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTipoPersonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vSuperOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTipoPersonaLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIngresar))
                        .addGap(8, 8, 8)
                        .addGroup(panelTipoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFarmacit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTipoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vSuperOfertasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vSuperOfertasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_vSuperOfertasMouseEntered

    private void vSuperOfertasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vSuperOfertasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_vSuperOfertasMouseExited

    private void txtNombreTipoPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTipoPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTipoPersonaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        tabla.setRowCount(0);
        controlarTipoPersona.controlarAccion(evt, obtenerTipoPersona());
        System.out.println("Dentre al boton ingresar");
        limpiarDatosTipoPersona();
        llenarTabla();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarDatosTipoPersona();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        controlarTipoPersona.controlarAccion(evt, obtenerTipoPersona());
        limpiarDatosTipoPersona();
        tabla.setRowCount(0);
        llenarTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        controlarTipoPersona.controlarAccion(evt, obtenerTipoPersona());
        limpiarDatosTipoPersona();
        tabla.setRowCount(0);
        llenarTabla();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        llenarTablaConBusqueda(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaDatosTipoPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosTipoPersonaMouseClicked
        // TODO add your handling code here:

        TipoPersona esteTipoPersona =new TipoPersona();
        if (evt.getClickCount()==2) {
            int fila = tablaDatosTipoPersona.rowAtPoint(evt.getPoint());

            if(fila > -1){

                spinnerId.setValue((Integer) tablaDatosTipoPersona.getValueAt(fila,0));
                txtNombreTipoPersona.setText(((String) tablaDatosTipoPersona.getValueAt(fila,1)));

                //
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);

                System.out.println("dentre a la funcion llenar la tabla con dos click");
                //                BTNModificar.setVisible(true);
                //                BTNModificar.seetrue);
        }//   17/10/2024 tenemos dos anos para para la practica enviar correo en el momento de entrar a practicas tiene que enviar un correo al sena para pedir instructor de seguimiento.
        // el id se esta pasando como cero hay que crear un objeto de la clase farmacia y traerlo y asinarselo ahi o mirar como lo hace en la guia
        }
    }//GEN-LAST:event_tablaDatosTipoPersonaMouseClicked

    private void labelFarmacitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFarmacitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelFarmacitMouseEntered

    private void labelFarmacitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFarmacitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelFarmacitMouseExited

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
       
        nuevaVentanaPersona = new DatosPersona();
        this.setVisible(false);
        nuevaVentanaPersona.setVisible(true);
        panelGeneral.add(nuevaVentanaPersona);
       
    }//GEN-LAST:event_formInternalFrameClosed
    
     private void limpiarDatosTipoPersona(){
        
        txtNombreTipoPersona.setText("");
        
    }
    
     private void llenarTabla(){
         
        TipoPersona unTipoPersona = new TipoPersona();
        tabla = (DefaultTableModel)tablaDatosTipoPersona.getModel();
        tabla.setRowCount(0);
        
        Iterator<TipoPersona> itTipoPersona = unTipoPersona.Listar();
        Object[] filaTipoPersona = new Object[2];
        
        while (itTipoPersona.hasNext()) {
            
            unTipoPersona = itTipoPersona.next();
            filaTipoPersona[0] = unTipoPersona.getIdTipoPersona();
            filaTipoPersona[1] = unTipoPersona.getNombreTipoPersona();
           
            
            tabla.addRow(filaTipoPersona);
          
        }
    }
     
    private TipoPersona obtenerTipoPersona (){
         
         TipoPersona elTipoPersona = new TipoPersona();
     
        
        elTipoPersona.setIdTipoPersona((Integer)spinnerId.getValue());
        elTipoPersona.setNombreTipoPersona(txtNombreTipoPersona.getText());

        return (elTipoPersona);
    }
    
     
     
     
     private void llenarTablaConBusqueda(String busqueda){
        
        TipoPersona unTipoPersona =new TipoPersona();
        DefaultTableModel tabla = (DefaultTableModel)tablaDatosTipoPersona.getModel();
        Iterator<TipoPersona> itTipoPersona = unTipoPersona.buscar(busqueda);
        Object[] filaTipoPersona = new Object [2];
        
        tabla.setRowCount(0); // es para limpiar la tabla 
        
        while (itTipoPersona.hasNext()){
            
            unTipoPersona = itTipoPersona.next();
            filaTipoPersona[0] = unTipoPersona.getIdTipoPersona();
            filaTipoPersona[1] = unTipoPersona.getNombreTipoPersona();
      
            
            tabla.addRow(filaTipoPersona);
        
        }
        
     
     }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelFarmacit;
    private javax.swing.JPanel panelTipoPersona;
    private javax.swing.JSpinner spinnerId;
    private javax.swing.JTable tablaDatosTipoPersona;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNombreTipoPersona;
    private javax.swing.JLabel vSuperOfertas;
    // End of variables declaration//GEN-END:variables
}
